baseURL: https://storopoli.io/
languageCode: en-us
theme: WonderMod
title: "Jose Storopoli, PhD"
copyright: '[CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)'

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableGitInfo: true

permalinks:
  posts: "/:filename"

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: "Jose Storopoli, PhD"
  description: "Computational Statistician, Pharmacometrician, STEM Educator, Opensource Contributor"
  keywords: [Statistics, Math, Blog, Research, Security, Privacy]
  author: "Jose Storopoli"
  DateFormat: "January 2, 2006"
  defaultTheme: dark # dark, light
  disableThemeToggle: false
  defaultTheme: auto

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowFullTextinRSS: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    disableHLJS: true
    disableFingerprinting: false
    favicon: "/assets/favicon.ico"
  
  profileMode:
    enabled: true
    #Title: "Hi I am Jose Storopoli"
    Subtitle: "Computational Statistician, Pharmacometrician, STEM Educator, Opensource Contributor."
    imageUrl: "/assets/pp.jpeg"
    imageTitle: "Profile Pic"
  
    buttons:
      - name: "Posts"
        url: "/posts"
      - name: "Julia for Data Science"
        url: "https://juliadatascience.io/"
      - name: "Bayesian Statistics"
        url: "https://github.com/storopoli/Bayesian-Statistics"

  socialIcons:
    - name: cv
      url: "https://github.com/storopoli/cv/raw/main/build/cv/cv.pdf"
    - name: github
      url: "https://github.com/storopoli"
    - name: linkedin
      url: "https://www.linkedin.com/in/storopoli"
    - name: youtube
      url: "https://www.youtube.com/channel/UCXJBhNvt4HUtPr0tR7w1r0g"
    - name: email
      url: "mailto:jose@storopoli.io"
    - name: rss
      url: /index.xml
    - name: pgpkey
      url: "/assets/publickey.txt"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/storopoli/storopoli.github.io/blob/main/content"
    Text: "Source code" # edit text
    appendFilePath: true # to append file path to Edit link

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "summary"]

#Enabling Search
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

markup:
  highlight:
    style: dracula
    noClasses: false
    guessSyntax: true

menu:
  main:
    - identifier: about
      name: about
      url: /about/
      weight: 10
    - identifier: cv
      name: cv
      url: https://github.com/storopoli/Bayesian-Statistics
      weight: 10
    - identifier: Search
      name: search
      url: /search/
      weight: 20
